[package]
name = "my_blog"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5.1", features = ["secrets"] }
rocket_dyn_templates = { version = "0.2.0", features = ["tera"] }
diesel = "2.1.6"
serde = { version = "1.0.130", features = ["derive"] }

